<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0p9bbaS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0p9bbaS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0p9bbaS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0p9bbaS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0p9bbaS\App_KernelDevDebugContainer([
    'container.build_hash' => '0p9bbaS',
    'container.build_id' => '3d5e44e8',
    'container.build_time' => 1612269734,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0p9bbaS');
