<?php

namespace Container0p9bbaS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TPtafGCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TPtafGC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TPtafGC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'club' => ['privates', '.errored..service_locator.TPtafGC.App\\Entity\\Club', NULL, 'Cannot autowire service ".service_locator.TPtafGC": it references class "App\\Entity\\Club" but no such service exists.'],
        ], [
            'club' => 'App\\Entity\\Club',
        ]);
    }
}
