<?php

namespace Container0p9bbaS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__3x5EJ0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..3x5EJ0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..3x5EJ0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'clubRepository' => ['privates', 'App\\Repository\\ClubRepository', 'getClubRepositoryService', true],
        ], [
            'clubRepository' => 'App\\Repository\\ClubRepository',
        ]);
    }
}
