<?php

namespace Container0p9bbaS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClubService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.TPtafGC.App\Entity\Club' shared service.
     *
     * @return \App\Entity\Club
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.TPtafGC": it references class "App\\Entity\\Club" but no such service exists.');
    }
}
